default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: localhost

development:
  <<: *default
  database: furima_42232_development

test:
  <<: *default
  database: furima_42232_test

production:
  <<: *default
  database: <%= ENV["FURIMA_42232_DATABASE"] %>
  username: <%= ENV["FURIMA_42232_USERNAME"] %>
  password: <%= ENV["FURIMA_42232_PASSWORD"] %>
  host: <%= ENV["FURIMA_42232_HOST"] %>